/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fastmenu;

import claseConectar.conectar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author maike
 */
public class MenuCliente extends javax.swing.JFrame {
    
    public static ArrayList<Pedidoslista> orden = new ArrayList<Pedidoslista>();
    public static DefaultListModel listModel = new DefaultListModel();
    static double totalOrder = 0;
    
    /**
     * Creates new form MenuCliente
     */
    public MenuCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        lista_pedidos.setModel(listModel);
    }
    
    public static void ADDlista_pedidos(String element){
        listModel.addElement(element);
        double getTotal = 0;
        for (int i = 0; i < orden.size(); i++) {
            getTotal = getTotal + orden.get(i).getTotal();
        }
        totalOrder = getTotal;
    }
    
    public static void removeList(int pos){
        listModel.removeElementAt(pos);
        double getTotal = 0;
        for (int i = 0; i < orden.size(); i++) {
            getTotal = getTotal + orden.get(i).getTotal();
        }
        totalOrder = getTotal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        goBebidas = new javax.swing.JButton();
        goPlatillos = new javax.swing.JButton();
        goPostres = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        cancel = new javax.swing.JButton();
        order = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista_pedidos = new javax.swing.JList<>();
        delete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mesa = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        MenuCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        goBebidas.setBackground(new java.awt.Color(0, 0, 0));
        goBebidas.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        goBebidas.setForeground(new java.awt.Color(255, 255, 255));
        goBebidas.setText("Bebida");
        goBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBebidasActionPerformed(evt);
            }
        });
        getContentPane().add(goBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 95, 70));

        goPlatillos.setBackground(new java.awt.Color(0, 0, 0));
        goPlatillos.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        goPlatillos.setForeground(new java.awt.Color(255, 255, 255));
        goPlatillos.setText("Platillos");
        goPlatillos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goPlatillosActionPerformed(evt);
            }
        });
        getContentPane().add(goPlatillos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 95, 70));

        goPostres.setBackground(new java.awt.Color(0, 0, 0));
        goPostres.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        goPostres.setForeground(new java.awt.Color(255, 255, 255));
        goPostres.setText("Postres");
        goPostres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goPostresActionPerformed(evt);
            }
        });
        getContentPane().add(goPostres, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 95, 70));

        description.setColumns(20);
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 480, 100));

        cancel.setBackground(new java.awt.Color(0, 0, 0));
        cancel.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancelar");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, -1, -1));

        order.setBackground(new java.awt.Color(0, 0, 0));
        order.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        order.setForeground(new java.awt.Color(255, 255, 255));
        order.setText("Ordenar");
        order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderActionPerformed(evt);
            }
        });
        getContentPane().add(order, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, -1, -1));

        lista_pedidos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        lista_pedidos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista_pedidosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lista_pedidos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 480, 90));

        delete.setBackground(new java.awt.Color(0, 0, 0));
        delete.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Borrar");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descripción");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 120, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mesa:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        mesa.setBackground(new java.awt.Color(153, 153, 153));
        mesa.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        mesa.setForeground(new java.awt.Color(255, 255, 255));
        mesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        getContentPane().add(mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 60, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Comida");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 80, -1));

        MenuCliente.setForeground(new java.awt.Color(0, 0, 0));
        MenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo cliente.jpg"))); // NOI18N
        getContentPane().add(MenuCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBebidasActionPerformed
        // TODO add your handling code here:
        ClientesBebidas abrir = new ClientesBebidas();
        abrir.setVisible(true);
    }//GEN-LAST:event_goBebidasActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        Inicio abrir = new Inicio();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderActionPerformed
        // TODO add your handling code here:
        if(orden.size() == 0){
            JOptionPane.showMessageDialog(null, "No puedes hacer, orden sin platillos");
        } else {
            //chekin de mesa
            String search = "SELECT * FROM pedidos";
            Statement st;
            ResultSet datos=null;
            boolean exist = false;
            try{
                st=cn.createStatement();
                datos=st.executeQuery(search);
                while (datos.next()) {
                    if(mesa.getSelectedItem().equals(datos.getString("mesa"))){
                        exist = true;
                    }
                }
            }catch(Exception e){ System.out.print(e.toString());}
            //verifica si la mesa existe
            if(exist == true){
                JOptionPane.showMessageDialog(null, "La orden de esta mesa ya existe");
            } else {
                //ingresa la orden en la bd
                String ordenPadre = "INSERT INTO `pedidos` (`id`, `mesa`, `descripcion`) VALUES (NULL, '"+mesa.getSelectedItem()+"', '"+description.getText()+"');";
                try{
                    JOptionPane.showMessageDialog(null, "Es un total de: "+totalOrder);
                    st=cn.createStatement();
                    st.execute(ordenPadre);
                    for (int i = 0; i < orden.size(); i++) {
                        String sql = "INSERT INTO `pedidoslista` (`id`, `id_pedido`, `id_platillo`, `nombre`, `tipo`, `cantidad`, `total`) VALUES (NULL, '"+mesa.getSelectedItem()+"', '"+orden.get(i).getIdPlatillo()+"', '"+orden.get(i).getTipo()+"', '"+orden.get(i).getNombre()+"', '"+orden.get(i).getCantidad()+"', '"+orden.get(i).getTotal()+"');";
                        st.execute(sql);
                    }
                    //limpiar todo
                    orden.clear();
                    listModel.removeAllElements();
                    description.setText("");
                }catch(Exception e){ System.out.print(e.toString());}
            }
        }
    }//GEN-LAST:event_orderActionPerformed
    
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        if(lista_pedidos.getSelectedIndex() != -1){
            orden.remove(lista_pedidos.getSelectedIndex());
            listModel.removeElementAt(lista_pedidos.getSelectedIndex());
            double getTotal = 0;
            for (int i = 0; i < orden.size(); i++) {
                getTotal = getTotal + orden.get(i).getTotal();
            }
            totalOrder = getTotal;
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void goPlatillosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goPlatillosActionPerformed
        // TODO add your handling code here:
        ClientesPlatillo abrir = new ClientesPlatillo();
        abrir.setVisible(true);
    }//GEN-LAST:event_goPlatillosActionPerformed

    private void goPostresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goPostresActionPerformed
        // TODO add your handling code here:
        ClientesPostre abrir = new ClientesPostre();
        abrir.setVisible(true);
    }//GEN-LAST:event_goPostresActionPerformed

    private void lista_pedidosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista_pedidosValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lista_pedidosValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenuCliente;
    private javax.swing.JButton cancel;
    private javax.swing.JButton delete;
    private javax.swing.JTextArea description;
    private javax.swing.JButton goBebidas;
    private javax.swing.JButton goPlatillos;
    private javax.swing.JButton goPostres;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    static javax.swing.JList<String> lista_pedidos;
    private javax.swing.JComboBox<String> mesa;
    private javax.swing.JButton order;
    // End of variables declaration//GEN-END:variables
    conectar mysql = new conectar();
    Connection cn = mysql.conexion();
}
