/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fastmenu;

import claseConectar.conectar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;

/**
 *
 * @author maike
 */
public class MenuChef extends javax.swing.JFrame {
    public static DefaultListModel listModel = new DefaultListModel();

    /**
     * Creates new form MenuChef
     */
    public MenuChef() {
        initComponents();
        this.setLocationRelativeTo(null);
        platillos.setModel(listModel);
        String sql = "SELECT * FROM pedidos";
        Statement st;
        ResultSet datos=null;
        try{
            st=cn.createStatement();
            datos=st.executeQuery(sql);
            while (datos.next()) {
                orderIndex.addItem(datos.getString("mesa"));
            }
        }catch(Exception e){ System.out.print(e.toString());}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        orderIndex = new javax.swing.JComboBox<>();
        fuckGoBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        platillos = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        finish = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        MenuChef = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cocina");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, -1));

        orderIndex.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        orderIndex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccionar" }));
        orderIndex.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                orderIndexItemStateChanged(evt);
            }
        });
        getContentPane().add(orderIndex, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 49, 200, -1));

        fuckGoBack.setBackground(new java.awt.Color(204, 0, 0));
        fuckGoBack.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 0, 18)); // NOI18N
        fuckGoBack.setForeground(new java.awt.Color(255, 255, 255));
        fuckGoBack.setText("Cerrar");
        fuckGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuckGoBackActionPerformed(evt);
            }
        });
        getContentPane().add(fuckGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mesa:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 60, -1));

        platillos.setBackground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(platillos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 275, 301));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Platillos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 80, -1));

        description.setEditable(false);
        description.setBackground(new java.awt.Color(153, 153, 153));
        description.setColumns(20);
        description.setRows(5);
        jScrollPane2.setViewportView(description);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 259, 301));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Descripción");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 110, -1));

        finish.setBackground(new java.awt.Color(0, 0, 0));
        finish.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        finish.setForeground(new java.awt.Color(255, 255, 255));
        finish.setText("Terminar Orden");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });
        getContentPane().add(finish, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 170, 90));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 60, 20));

        total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 200, -1));

        MenuChef.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Enrique\\Desktop\\interfaces\\imagen proyect\\Menu Chef.jpg")); // NOI18N
        getContentPane().add(MenuChef, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderIndexItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_orderIndexItemStateChanged
        // TODO add your handling code here:
        listModel.removeAllElements();
        description.setText("");
        total.setText("");
        if(!orderIndex.getSelectedItem().equals("seleccionar")){
            String sql = "SELECT * FROM pedidos WHERE mesa = '"+orderIndex.getSelectedItem()+"'";
            Statement st;
            ResultSet datos=null;
            ResultSet data=null;
            double totaldata = 0;
            try{
                st=cn.createStatement();
                datos=st.executeQuery(sql);
                while (datos.next()) {
                    description.setText(datos.getString("descripcion"));
                }
                //añadir platillo
                String xd = "SELECT * FROM pedidoslista WHERE id_pedido = '"+orderIndex.getSelectedItem()+"'";
                data=st.executeQuery(xd);
                while (data.next()) {
                    listModel.addElement(data.getString("nombre")+" x"+data.getString("cantidad")+" "+data.getString("total")+"$");
                        totaldata = totaldata + Double.parseDouble(data.getString("total"));
                }
                total.setText(Double.toString(totaldata));
            }catch(Exception e){ System.out.print(e.toString());}
        }
    }//GEN-LAST:event_orderIndexItemStateChanged

    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        // TODO add your handling code here:
        if(!orderIndex.getSelectedItem().equals("seleccionar")){
            String sql = "DELETE FROM pedidos WHERE mesa = "+orderIndex.getSelectedItem();
            Statement st;
            try{
                st=cn.createStatement();
                st.executeUpdate(sql);
                //
                String mysql = "DELETE FROM pedidoslista WHERE id_pedido = "+orderIndex.getSelectedItem();
                st.executeUpdate(mysql);
                
                orderIndex.removeItemAt(orderIndex.getSelectedIndex());
                orderIndex.setSelectedIndex(0);
                listModel.removeAllElements();
                total.setText("");
            }catch(Exception e){ System.out.print(e.toString());}
        }
    }//GEN-LAST:event_finishActionPerformed

    private void fuckGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuckGoBackActionPerformed
        // TODO add your handling code here:
        Inicio abrir = new Inicio();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_fuckGoBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuChef().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenuChef;
    private javax.swing.JTextArea description;
    private javax.swing.JButton finish;
    private javax.swing.JButton fuckGoBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> orderIndex;
    private javax.swing.JList<String> platillos;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
    conectar mysql = new conectar();
    Connection cn = mysql.conexion();
}
