/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fastmenu;

import javax.swing.JFrame;

/**
 *
 * @author maike
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salir = new javax.swing.JButton();
        Platillos = new javax.swing.JButton();
        Chefs = new javax.swing.JButton();
        MenuAdministrador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setBackground(new java.awt.Color(255, 0, 0));
        Salir.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 0, 18)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Cerrar");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        Platillos.setBackground(new java.awt.Color(0, 0, 0));
        Platillos.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Platillos.setForeground(new java.awt.Color(255, 255, 255));
        Platillos.setText("Platillos");
        Platillos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlatillosActionPerformed(evt);
            }
        });
        getContentPane().add(Platillos, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 160, 100, -1));

        Chefs.setBackground(new java.awt.Color(0, 0, 0));
        Chefs.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Chefs.setForeground(new java.awt.Color(255, 255, 255));
        Chefs.setText("Chefs");
        Chefs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChefsActionPerformed(evt);
            }
        });
        getContentPane().add(Chefs, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 100, -1));

        MenuAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Manu Administrador.jpg"))); // NOI18N
        getContentPane().add(MenuAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChefsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChefsActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        frame.setContentPane(new AdminChefs());
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_ChefsActionPerformed

    private void PlatillosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlatillosActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        frame.setContentPane(new AdminPlatillos());
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_PlatillosActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        Inicio abrir = new Inicio();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Chefs;
    private javax.swing.JLabel MenuAdministrador;
    private javax.swing.JButton Platillos;
    private javax.swing.JButton Salir;
    // End of variables declaration//GEN-END:variables
}
