/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fastmenu;

import java.awt.EventQueue;
import java.util.ArrayList;

/**
 *
 * @author maike
 */
public class NewJPanel extends javax.swing.JFrame {

    /**
     * Creates new form NewJPanel
     */
    static ArrayList<NewJPanelPlatillo> platillos=new ArrayList();
    NewJPanelPlatillo platilloVisual;
    
    
    public NewJPanel() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(600, 425));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));
        add(jPanel1);
        jPanel1.setBounds(200, 80, 410, 260);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(87, 88, 73, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu plat=new Menu(5, "55555", "xd", 40);
        platilloVisual=new NewJPanelPlatillo(plat);
        jPanel1.add(platilloVisual);
        this.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public static void main(String[] args) {
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewJPanel();
                 }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public static javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
